pipeline:
  name: Build Test
  identifier: Build_Test_1774618881372
  template:
    templateRef: First_Pipeline_Created
    versionLabel: V1
    templateInputs:
      properties:
        ci:
          codebase:
            build: <+input>
  projectIdentifier: Assignment_Vanshika
  orgIdentifier: default
